modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "hexxyinthealps"
version = "${version}"
displayName = "Hexxy Searches For A Lost Cat In The Alps"
logoFile = "assets/hexxyinthealps/icon.png"
authors = "object-Object"
description = "A server-side per-player hex profiler and lag detector for Hex Casting."

[[dependencies.hexxyinthealps]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexxyinthealps]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexxyinthealps]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexxyinthealps]]
modId = "cloth_config"
mandatory = true
versionRange = "[${versions.cloth_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexxyinthealps]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexxyinthealps]]
modId = "complexhex"
mandatory = false
versionRange = "[${versions.complexHex},)"
ordering = "NONE"
side = "BOTH"
