modid = "hexxyinthealps"
book = "hexcasting:thehexbook"

resource_dirs = [  # top takes priority
    "resources",
    "{$_common.src}/main/resources",
    { path="{$_common.src}/generated/resources", required=false },
    "{$_fabric.src}/main/resources",
    { path="{$_fabric.src}/generated/resources", required=false },
    "{$_forge.src}/main/resources",
    { path="{$_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexxyinthealps/_export/generated"

[template]
icon = "{$_common.src}/main/resources/assets/hexxyinthealps/icon.png"
include = [
    "hexxyinthealps",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hexxy Searches For A Lost Cat In The Alps"
author = "object-Object"
show_landing_text = false

[extra.hexcasting]
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\("(?P<name>[^"]+)",\s*HexDir\.(?P<startdir>\w+),\s*"(?P<signature>[qweasd]+)"' }

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.kotlin}/registry/HexxyInTheAlpsActions.kt"
regex = "{^_pattern_regex}"

# platforms

[_common]
src = "../Common/src"
java = "{src}/main/java/gay/object/hexxyinthealps"
kotlin = "{src}/main/kotlin/gay/object/hexxyinthealps"

[_fabric]
src = "../Fabric/src"
java = "{src}/main/java/gay/object/hexxyinthealps/fabric"
kotlin = "{src}/main/kotlin/gay/object/hexxyinthealps/fabric"

[_forge]
src = "../Forge/src"
java = "{src}/main/java/gay/object/hexxyinthealps/forge"
kotlin = "{src}/main/kotlin/gay/object/hexxyinthealps/forge"
